# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73aa5d0039cd39e80e0b89cac793e0b2c3e19cdd0f20f863f1eaa209c2c3ce00a7cec8d7464a6642a87ad3cc5524827d273a2ffe87085d4e4791961c241693a

test:
  secret_key_base: 3509a889bab7dfe11e17f8c042c9a917867a413ae62ff8706805beb903ff8a8443a883830c5ae52fb8c29aaf2ce213e96794721ba7d186601c3b988ba5febcbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
